### ISSUE TITLE
Missing src/images/photo{1,2,3}.jpg

### ISSUE THREAD

**Issue by jevakallio** [kelset/react-native-glshaders-testing#1]
Running the app fails with 
```
Unable to resolve module `./images/photo1.jpg`
```

Photos 2 and 3 missing, too.

**Comment by kelset** [comment]
I don't know why GitHub doesn't notify me of issues in my own repo, but anyway I finally noticed it.

Yes the reason why it doesn't show you the images is that the `images` folder is gitignored, to avoid to have the repo being too heavy ;)
@brentvatne's version of it has the photos back and he made it work with expo, [here](https://github.com/brentvatne/react-native-glshaders-testing).
