### ISSUE TITLE
Example on expo

### ISSUE THREAD

**Issue by Angelk90** [kelset/react-native-glshaders-testing#3]
@kelset : 
Hi, it would be possible to have an example on a working expo.
As seen in the image:
https://github.com/kelset/react-native-glshaders-testing/blob/master/preview.gif
https://github.com/kelset/react-native-glshaders-testing/blob/master/preview.gif?raw=true

**Comment by kelset** [comment]
Hi, this example is quite old so I'd have to re-do it probably. At the moment I don't have time for that, but [this article has a similar approach](https://blog.expo.io/filtering-images-with-expo-ffd8f053bc85) and works ;)

**Comment by Angelk90** [comment]
@kelset : 
You could publish it anyway to give it a look, better to have nothing.
P.Š.
There are no compatiety problems on android, right?
